baseURL = "https://singalhimanshu.github.io"
languageCode = "en-us"
title = "singalhimanshu"
theme = "cactus"
copyright = "singalhimanshu"
disqusShortname = "singalhimanshu"
# googleAnalytics = ""


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Resume"
url = "https://drive.google.com/file/d/1qKGwczUTAritrH6VwVYHTcOCm5a0Gqb4/view"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]
  colortheme = "classic" # dark, light, white, or classic
  rss = true
  googleAnalyticsAsync = true
  showAllPostsArchive = false # default

  # Home page settings
  description = "Hello, I'm Himanshu. I'm currently doing Master's in Computer Science from Department of Computer Science, University of Delhi. I'm interested in software development, I like writing terminal applications, games and recently I have been contributing to an open source project [quick-lint-js](https://github.com/quick-lint/quick-lint-js) which is a javascript bug finding tool."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  tagsOverview = true
  showProjectsList = true
  projectsUrl = "https://github.com/singalhimanshu"

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02"

  # Post page settings
  show_updated = true
  showReadTime = true

  [params.comments]
    enabled = false
    engine = "disqus"

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/singalhimanshu"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/singalhimanshu"
  [[params.social]]
    name = "email"
    link = "himanshus.mcs20.du@gmail.com"
